USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS MUDIT_TEST_RM FREQUENCY = MONTHLY, START_TIMESTAMP = IMMEDIATELY, NOTIFY_USERS = null TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO NOTIFY;
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS WH_MUDIT_TEST INITIALLY_SUSPENDED = true, SCALING_POLICY = 'ECONOMY', AUTO_SUSPEND = 600, AUTO_RESUME = true, WAREHOUSE_SIZE = 'XSMALL', MIN_CLUSTER_COUNT = 1, MAX_CLUSTER_COUNT = 1;
USE ROLE ACCOUNTADMIN;
ALTER WAREHOUSE IF EXISTS WH_MUDIT_TEST SET RESOURCE_MONITOR = MUDIT_TEST_RM;
